### ISSUE TITLE
How to vary API base address by environment?

### ISSUE THREAD

**Issue by ardalis** [Blazor-School/api-interaction-blazor-wasm-dotnet6#1]
Let's say I have multiple environments, localhost, a dev server, a stage server, and a production server. I want to specify a different base address for http client for each of these. Where do I put this so the webassembly project uses the correct base address in the correct environment?

See: https://github.com/Blazor-School/api-interaction-blazor-wasm-dotnet6/blob/master/ApiInteraction/Program.cs

**Comment by hevilhuy** [comment]
You will introduce appsettings.json. Anyway, we don't use GitHub to ask and answer. Join the community if you have questions.
https://discord.com/invite/HsTu2Emqsd

**Comment by ardalis** [comment]
Great, thanks. I've joined and asked.
